#Use a base image
FROM ubuntu:latest

#set the working directory inside the container
WORKDIR /app

#copy the file from the host into the container
COPY . /app

#run a command inside the container
CMD ["echo", "Hello Azubi's finest"]

